name: Kalinowski Photo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4475681302137673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#caddee'
    - '#99b8d8'
    - '#5783b1'
    - '#233951'
    - '#071526'
  brandStrength: 0.5625
  lightness: 0.3547032254282385
  saturation: 0.2691349405795336
  rhythmicContrast: 0.6984094453509897
purpose: []
